"use client";
import { useEffect, useState } from "react";
export type Language = "vi" | "en";
const en = { transactions:"Transactions", accounts:"Accounts", categories:"Categories", assets:"Assets", data:"Data", review:"Review", portfolio:"Portfolio", title:"Personal Finance", eyebrow:"Local-first ledger", language:"Language" } as const;
const vi = { transactions:"Giao dịch", accounts:"Tài khoản", categories:"Danh mục", assets:"Tài sản", data:"Dữ liệu", review:"Đối soát", portfolio:"Đầu tư", title:"Tài chính cá nhân", eyebrow:"Sổ cái lưu trữ cục bộ", language:"Ngôn ngữ" } as const;
export const copy = { en, vi } as const;
export const display = {
  en: (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, c => c.toUpperCase()),
  vi: (value: string) => ({ CASH:"Tiền mặt", BANK:"Ngân hàng", CREDIT_CARD:"Thẻ tín dụng", EWALLET:"Ví điện tử", EXPENSE:"Chi tiêu", INCOME:"Thu nhập", TRANSFER:"Chuyển tiền", CREDIT_CARD_PAYMENT:"Thanh toán thẻ tín dụng", INTEREST:"Tiền lãi", SAVINGS_DEPOSIT:"Gửi tiết kiệm", SAVINGS_WITHDRAWAL:"Rút tiết kiệm", ASSET_PURCHASE:"Mua tài sản", ASSET_SALE:"Bán tài sản", ADJUSTMENT:"Điều chỉnh", LIVE:"Trực tiếp", STALE:"Cũ", MANUAL:"Nhập thủ công", UNAVAILABLE:"Không khả dụng", RAW:"Nguyên liệu", ACTIVE:"Đang hoạt động", EARLY_CLOSED:"Tất toán trước hạn", OPEN:"Đang mở", CLOSED:"Đã đóng", AT_MATURITY:"Cuối kỳ", UPFRONT:"Trả trước", PERIODIC:"Định kỳ", RENEW_PRINCIPAL:"Tái tục gốc", RENEW_PRINCIPAL_AND_INTEREST:"Tái tục gốc & lãi", CLOSE:"Không tự động tái tục", ACTUAL_365:"Thực tế/365", ACTUAL_360:"Thực tế/360", THIRTY_360:"30/360" } as Record<string,string>)[value] ?? value,
} as const;
export function enumLabel(language: Language, value: string): string {
  return display[language](value);
}
export const defaultCategoryLabels = {
  "Expenses":"Chi tiêu", "Income":"Thu nhập", "Food & Drinks":"Ăn uống", "Groceries":"Đi chợ / Siêu thị", "Eating Out":"Ăn ngoài", "Coffee & Drinks":"Cà phê & Đồ uống", "Bills & Utilities":"Hóa đơn & Tiện ích", "Electricity":"Điện", "Water":"Nước", "Internet":"Internet", "Mobile Phone":"Điện thoại di động", "Rent":"Tiền thuê nhà", "Gas":"Gas / Khí đốt", "Transportation":"Di chuyển", "Fuel":"Nhiên liệu", "Parking":"Gửi xe", "Taxi & Ride-hailing":"Taxi & Xe công nghệ", "Public Transport":"Phương tiện công cộng", "Vehicle Maintenance":"Bảo dưỡng xe", "Shopping":"Mua sắm", "Clothing":"Quần áo", "Electronics":"Điện tử", "Personal Items":"Đồ dùng cá nhân", "Household":"Đồ gia dụng", "Home & Family":"Nhà cửa & Gia đình", "Home Maintenance":"Bảo trì nhà cửa", "Family":"Gia đình", "Children":"Con cái", "Pets":"Thú cưng", "Health & Fitness":"Sức khỏe", "Medical":"Khám chữa bệnh", "Pharmacy":"Thuốc", "Fitness":"Thể dục", "Entertainment":"Giải trí", "Movies & Events":"Phim & Sự kiện", "Games":"Trò chơi", "Subscriptions":"Dịch vụ đăng ký", "Hobbies":"Sở thích", "Education":"Giáo dục", "Tuition":"Học phí", "Books":"Sách", "Courses":"Khóa học", "Travel":"Du lịch", "Flights":"Vé máy bay", "Accommodation":"Lưu trú", "Local Transport":"Di chuyển tại điểm đến", "Activities":"Hoạt động", "Gifts & Donations":"Quà tặng & Từ thiện", "Gifts":"Quà tặng", "Charity":"Từ thiện", "Insurance":"Bảo hiểm", "Taxes & Fees":"Thuế & Phí", "Other Expense":"Chi tiêu khác", "Salary":"Lương", "Bonus":"Thưởng", "Business Income":"Thu nhập kinh doanh", "Investment Income":"Thu nhập đầu tư", "Interest":"Tiền lãi", "Gifts Received":"Quà tặng nhận được", "Refunds":"Hoàn tiền", "Other Income":"Thu nhập khác",
  "Debt Repayment":"Trả nợ", "Loans Given":"Cho vay", "Investments":"Đầu tư", "Crypto":"Tiền mã hóa", "Crypto Gains":"Lãi tiền mã hóa", "Paid on Behalf":"Chi hộ", "Loans & Debt Collection":"Vay & Thu nợ", "Collected on Behalf":"Thu hộ"
} as const;
export function categoryLabel(language: Language, name: string): string {
  return language === "vi" && name in defaultCategoryLabels ? defaultCategoryLabels[name as keyof typeof defaultCategoryLabels] : name;
}
const enUi = {
  "Main navigation":"Main navigation", "Import & reconciliation review":"Import & reconciliation review", "Persisted import batches and reconciliation candidates.":"Persisted import batches and reconciliation candidates.", "Import batches":"Import batches", "No import batches yet.":"No import batches yet.", "Reconciliation candidates":"Reconciliation candidates", "No reconciliation candidates yet.":"No reconciliation candidates yet.", "Raw row":"Raw row", "Event":"Event", "rows":"rows", "Portfolio & net worth":"Portfolio & net worth", "Current persisted balances and accepted valuations.":"Current persisted balances and accepted valuations.", "Net worth":"Net worth", "Accounts in scope":"Accounts in scope", "Invested assets":"Invested assets", "Valuation incomplete":"Valuation incomplete", "Valuation incomplete: one or more invested assets has no usable quote.":"Valuation incomplete: one or more invested assets has no usable quote.", "Valuation unavailable":"Valuation unavailable", "Savings":"Savings", "Credit cards":"Credit cards", "Precious metals":"Precious metals", "Crypto":"Crypto", "No savings yet.":"No savings yet.", "No credit cards yet.":"No credit cards yet.", "No precious metals yet.":"No precious metals yet.", "No crypto yet.":"No crypto yet.", "Accounts":"Accounts", "Create, edit, or deactivate the accounts used by ledger entries.":"Create, edit, or deactivate the accounts used by ledger entries.", "Name":"Name", "Type":"Type", "Currency":"Currency", "Save changes":"Save changes", "Add account":"Add account", "Cancel":"Cancel", "No accounts yet.":"No accounts yet.", "Edit":"Edit", "Deactivate":"Deactivate", "Activate":"Activate", "Categories":"Categories", "Organize events into an optional hierarchy.":"Organize events into an optional hierarchy.", "Parent":"Parent", "None":"None", "Add category":"Add category", "No categories yet.":"No categories yet.", "Top level":"Top level", "Transactions":"Transactions", "Record events with exact signed decimal amounts; validation and balances remain on the server.":"Record events with exact signed decimal amounts; validation and balances remain on the server.", "Date":"Date", "Category":"Category", "Payee":"Payee", "Trip / event":"Trip / event", "Note":"Note", "Account entries":"Account entries", "Select account":"Select account", "Signed amount":"Signed amount", "Remove":"Remove", "Remove entry":"Remove entry", "Add another entry":"Add another entry", "Record transaction":"Record transaction", "No transactions yet.":"No transactions yet.", "Details":"Details", "Entries":"Entries", "Saving…":"Saving…", "Active":"Active", "Inactive":"Inactive", "Loading…":"Loading…", "Load failed":"Load failed", "No provider":"No provider", "No quote timestamp":"No quote timestamp", "Account":"Account"
  , "Add details":"Add details", "Hide details":"Hide details", "Choose category":"Choose category", "Search category":"Search category", "Collapse":"Collapse", "Expand":"Expand", "All":"All", "Expenses":"Expenses", "Income":"Income", "Add child category":"Add child category", "Other / Unclassified":"Other / Unclassified", "No categories found.":"No categories found.", "Bank template":"Bank template", "Choose bank template":"Choose bank template", "Search banks":"Search banks", "Transfer":"Transfer", "From account":"From account", "To account":"To account", "Amount":"Amount", "Choose two different accounts":"Choose two different accounts", "Import from Money Lover":"Import from Money Lover", "Choose file":"Choose file", "Upload for review":"Upload for review", "Imported rows":"Imported rows", "Export CSV":"Export CSV", "Export XLSX":"Export XLSX", "Imported rows remain raw until reviewed and reconciled.":"Imported rows remain raw until reviewed and reconciled.", "Matching rows are applied straight into your ledger on upload; unmatched wallets are reported so you can fix and re-apply from the Review page.":"Matching rows are applied straight into your ledger on upload; unmatched wallets are reported so you can fix and re-apply from the Review page.", "Manage savings, precious metals, and crypto using persisted portfolio data.":"Manage savings, precious metals, and crypto using persisted portfolio data.", "Add savings":"Add savings", "Institution":"Institution", "Principal":"Principal", "Add gold / silver":"Add gold / silver", "Gold":"Gold", "Silver":"Silver", "Product":"Product", "Grams":"Grams", "Purity":"Purity", "Purchase price":"Purchase price", "Total cost":"Total cost", "Add crypto":"Add crypto", "Crypto quantity":"Crypto quantity", "Add":"Add"
  , "Product catalog":"Product catalog", "Quantity":"Quantity", "Quantity (chỉ)":"Quantity (chỉ)", "Choose coin":"Choose coin", "Search coin":"Search coin", "Coin catalog unavailable":"Coin catalog unavailable"
  , "Add savings account":"Add savings account", "Edit savings account":"Edit savings account", "Savings account details":"Savings account details", "Total principal":"Total principal", "Accounts maturing soon":"Accounts maturing soon", "Savings account name":"Savings account name", "Savings product":"Savings product", "Deposit amount":"Deposit amount", "Source account":"Source account", "Deposit date":"Deposit date", "Term (months)":"Term (months)", "Annual interest rate (%/year)":"Annual interest rate (%/year)", "Demand interest rate (%/year)":"Demand interest rate (%/year)", "Interest payment method":"Interest payment method", "On maturity":"On maturity", "Save savings account":"Save savings account", "Close dialog":"Close dialog", "Settle":"Settle", "Early settle":"Early settle", "Renew":"Renew", "Settlement date":"Settlement date", "Receiving account":"Receiving account", "Actual interest received":"Actual interest received", "Fee (optional)":"Fee (optional)", "Renewal start date":"Renewal start date", "Current principal":"Current principal", "Projected value at maturity":"Projected value at maturity", "Term history":"Term history", "Term":"Term", "Remaining":"Remaining", "days":"days", "months":"months", "Ongoing":"Ongoing", "Maturing soon":"Maturing soon", "Matured":"Matured", "Settled":"Settled", "Settled early":"Settled early", "No wallet accounts available. Create a cash, bank, or e-wallet account first.":"No wallet accounts available. Create a cash, bank, or e-wallet account first.", "No terms recorded yet.":"No terms recorded yet.", "This savings account has lifecycle history and can no longer be edited directly; use Settle or Renew instead.":"This savings account has lifecycle history and can no longer be edited directly; use Settle or Renew instead.", "No savings accounts yet.":"No savings accounts yet.", "Expected interest":"Expected interest", "Interest rate":"Interest rate", "Bank / Institution":"Bank / Institution", "Maturity date":"Maturity date", "Notes":"Notes"
  , "Edit account":"Edit account", "Current balance":"Current balance", "Adjust balance":"Adjust balance", "New balance":"New balance", "Difference":"Difference", "Adjustment date":"Adjustment date", "No change to save.":"No change to save.", "Credit card":"Credit card", "Payment amount":"Payment amount", "No credit card accounts available. Create one first.":"No credit card accounts available. Create one first."
  , "Create, edit, or deactivate the accounts used by ledger entries. Order here also sets the order accounts appear in when recording a transaction.":"Create, edit, or deactivate the accounts used by ledger entries. Order here also sets the order accounts appear in when recording a transaction.", "Move up":"Move up", "Move down":"Move down"
  , "Icon":"Icon", "Automatic (by name)":"Automatic (by name)", "Previous day":"Previous day", "Next day":"Next day", "Choose date":"Choose date", "Add a note":"Add a note"
  , "Uploading...":"Uploading...", "Data":"Data", "Import and export personal finance records.":"Import and export personal finance records."
  , "Apply":"Apply", "Re-apply":"Re-apply", "Applying...":"Applying...", "Applied":"Applied", "applied":"applied", "rows with unmatched wallet":"rows with unmatched wallet", "invalid rows":"invalid rows"
  , "Choose an account":"Choose an account", "Enter an amount":"Enter an amount", "Choose a category":"Choose a category"
  , "Delete":"Delete", "Confirm delete":"Confirm delete", "Deleting...":"Deleting...", "Transaction details":"Transaction details", "Editing transaction":"Editing transaction", "This transaction type is managed on its own page and can't be edited or deleted here.":"This transaction type is managed on its own page and can't be edited or deleted here."
  , "Assets":"Assets", "Manage assets, investments, and net worth in one place.":"Manage assets, investments, and net worth in one place."
} as const;
export type UiKey = keyof typeof enUi;
export const transactionUiKeys = {
  accountEntries: "Account entries",
  selectAccount: "Select account",
  addAnotherEntry: "Add another entry",
  addDetails: "Add details",
  hideDetails: "Hide details",
  loadFailed: "Load failed",
} as const satisfies Record<string, UiKey>;
const viUi: Record<string, string> = {
  "Main navigation":"Điều hướng chính", "Import & reconciliation review":"Xem lại nhập liệu & đối soát", "Persisted import batches and reconciliation candidates.":"Các đợt nhập liệu và ứng viên đối soát đã lưu.", "Import batches":"Các đợt nhập liệu", "No import batches yet.":"Chưa có đợt nhập liệu nào.", "Reconciliation candidates":"Ứng viên đối soát", "No reconciliation candidates yet.":"Chưa có ứng viên đối soát nào.", "Raw row":"Dòng thô", "Event":"Sự kiện", "rows":"dòng", "Portfolio & net worth":"Danh mục đầu tư & tài sản ròng", "Current persisted balances and accepted valuations.":"Số dư đã lưu và định giá được chấp nhận hiện tại.", "Net worth":"Tài sản ròng", "Accounts in scope":"Tài khoản trong phạm vi", "Invested assets":"Tài sản đầu tư", "Valuation incomplete":"Định giá chưa đầy đủ", "Valuation incomplete: one or more invested assets has no usable quote.":"Định giá chưa đầy đủ: một hoặc nhiều tài sản đầu tư không có báo giá dùng được.", "Valuation unavailable":"Không thể định giá", "Savings":"Tiết kiệm", "Credit cards":"Thẻ tín dụng", "Precious metals":"Kim loại quý", "Crypto":"Tiền mã hóa", "No savings yet.":"Chưa có khoản tiết kiệm nào.", "No credit cards yet.":"Chưa có thẻ tín dụng nào.", "No precious metals yet.":"Chưa có kim loại quý nào.", "No crypto yet.":"Chưa có tiền mã hóa nào.", "Accounts":"Tài khoản", "Create, edit, or deactivate the accounts used by ledger entries.":"Tạo, sửa hoặc ngừng kích hoạt tài khoản dùng cho giao dịch.", "Name":"Tên", "Type":"Loại", "Currency":"Tiền tệ", "Save changes":"Lưu thay đổi", "Add account":"Thêm tài khoản", "Cancel":"Hủy", "No accounts yet.":"Chưa có tài khoản nào.", "Edit":"Sửa", "Deactivate":"Ngừng kích hoạt", "Activate":"Kích hoạt", "Categories":"Danh mục", "Organize events into an optional hierarchy.":"Sắp xếp sự kiện theo hệ thống phân cấp tùy chọn.", "Parent":"Danh mục cha", "None":"Không có", "Add category":"Thêm danh mục", "No categories yet.":"Chưa có danh mục nào.", "Top level":"Cấp cao nhất", "Transactions":"Giao dịch", "Record events with exact signed decimal amounts; validation and balances remain on the server.":"Ghi sự kiện với số tiền thập phân có dấu chính xác; máy chủ chịu trách nhiệm xác thực và số dư.", "Date":"Ngày", "Category":"Danh mục", "Payee":"Người nhận", "Trip / event":"Chuyến đi / sự kiện", "Note":"Ghi chú", "Account entries":"Tài khoản giao dịch", "Select account":"Chọn tài khoản", "Signed amount":"Số tiền", "Remove":"Xóa", "Remove entry":"Xóa dòng giao dịch", "Add another entry":"Thêm dòng giao dịch", "Record transaction":"Ghi giao dịch", "No transactions yet.":"Chưa có giao dịch nào.", "Details":"Chi tiết", "Entries":"Dòng giao dịch", "Saving…":"Đang lưu…", "Active":"Đang hoạt động", "Inactive":"Ngừng hoạt động", "Loading…":"Đang tải…", "Load failed":"Tải dữ liệu thất bại", "No provider":"Không có nhà cung cấp", "No quote timestamp":"Không có thời điểm báo giá", "Account":"Tài khoản"
  , "Add details":"Thêm chi tiết", "Hide details":"Ẩn chi tiết", "Choose category":"Chọn danh mục", "Bank template":"Ngân hàng mẫu", "Choose bank template":"Chọn ngân hàng mẫu", "Search banks":"Tìm ngân hàng", "Transfer":"Chuyển tiền", "From account":"Từ tài khoản", "To account":"Đến tài khoản", "Amount":"Số tiền", "Choose two different accounts":"Hãy chọn hai tài khoản khác nhau", "Import from Money Lover":"Nhập từ Money Lover", "Choose file":"Chọn tệp", "Upload for review":"Tải lên để xem xét", "Imported rows":"Dòng đã nhập", "Export CSV":"Xuất CSV", "Export XLSX":"Xuất XLSX", "Imported rows remain raw until reviewed and reconciled.":"Dòng nhập vẫn ở dạng thô cho đến khi được xem xét và đối soát.", "Matching rows are applied straight into your ledger on upload; unmatched wallets are reported so you can fix and re-apply from the Review page.":"Các dòng khớp ví sẽ được đưa thẳng vào giao dịch ngay khi tải lên; ví chưa khớp sẽ được báo lại để bạn sửa rồi đưa lại từ trang Xem lại nhập liệu.", "Manage savings, precious metals, and crypto using persisted portfolio data.":"Quản lý tiết kiệm, kim loại quý và tiền mã hóa bằng dữ liệu danh mục đã lưu.", "Add savings":"Thêm khoản tiết kiệm", "Institution":"Ngân hàng / Tổ chức", "Principal":"Tiền gốc", "Add gold / silver":"Thêm vàng / bạc", "Gold":"Vàng", "Silver":"Bạc", "Product":"Sản phẩm", "Grams":"Gam", "Purity":"Độ tinh khiết", "Purchase price":"Giá mua", "Total cost":"Tổng chi phí", "Add crypto":"Thêm tiền mã hóa", "Crypto quantity":"Số lượng tiền mã hóa", "Add":"Thêm"
  , "Product catalog":"Danh mục sản phẩm", "Quantity":"Số lượng", "Quantity (chỉ)":"Số lượng (chỉ)", "Choose coin":"Chọn coin", "Search coin":"Tìm coin", "Coin catalog unavailable":"Không thể tải danh sách coin"
  , "Add savings account":"Thêm sổ tiết kiệm", "Edit savings account":"Chỉnh sửa sổ tiết kiệm", "Savings account details":"Chi tiết sổ tiết kiệm", "Total principal":"Tổng tiền gốc đang gửi", "Accounts maturing soon":"Số sổ sắp đáo hạn", "Savings account name":"Tên sổ", "Savings product":"Sản phẩm tiết kiệm", "Deposit amount":"Số tiền gửi", "Source account":"Tài khoản nguồn", "Deposit date":"Ngày gửi", "Term (months)":"Kỳ hạn (tháng)", "Annual interest rate (%/year)":"Lãi suất năm (%/năm)", "Demand interest rate (%/year)":"Lãi suất không kỳ hạn (%/năm)", "Interest payment method":"Phương thức trả lãi", "On maturity":"Khi đáo hạn", "Save savings account":"Lưu sổ", "Close dialog":"Đóng", "Settle":"Tất toán", "Early settle":"Tất toán trước hạn", "Renew":"Tái tục", "Settlement date":"Ngày tất toán", "Receiving account":"Tài khoản nhận", "Actual interest received":"Lãi thực nhận", "Fee (optional)":"Phí (nếu có)", "Renewal start date":"Ngày bắt đầu kỳ mới", "Current principal":"Tiền gốc hiện tại", "Projected value at maturity":"Giá trị dự kiến khi đáo hạn", "Term history":"Lịch sử kỳ gửi", "Term":"Kỳ", "Remaining":"Còn lại", "days":"ngày", "months":"tháng", "Ongoing":"Còn hạn", "Maturing soon":"Sắp đáo hạn", "Matured":"Đã đáo hạn", "Settled":"Đã tất toán", "Settled early":"Tất toán trước hạn", "No wallet accounts available. Create a cash, bank, or e-wallet account first.":"Chưa có tài khoản tiền mặt/ngân hàng/ví điện tử. Hãy tạo tài khoản trước.", "No terms recorded yet.":"Chưa có kỳ gửi nào.", "This savings account has lifecycle history and can no longer be edited directly; use Settle or Renew instead.":"Sổ đã có lịch sử nghiệp vụ nên không thể sửa trực tiếp; hãy dùng Tất toán hoặc Tái tục.", "No savings accounts yet.":"Chưa có sổ tiết kiệm nào.", "Expected interest":"Lãi dự kiến", "Interest rate":"Lãi suất", "Bank / Institution":"Ngân hàng / Tổ chức", "Maturity date":"Ngày đáo hạn", "Notes":"Ghi chú"
  , "Edit account":"Sửa tài khoản", "Current balance":"Số dư hiện tại", "Adjust balance":"Điều chỉnh số dư", "New balance":"Số dư mới", "Difference":"Chênh lệch", "Adjustment date":"Ngày điều chỉnh", "No change to save.":"Không có thay đổi để lưu.", "Credit card":"Thẻ tín dụng", "Payment amount":"Số tiền thanh toán", "No credit card accounts available. Create one first.":"Chưa có thẻ tín dụng nào. Hãy tạo tài khoản thẻ tín dụng trước."
  , "Create, edit, or deactivate the accounts used by ledger entries. Order here also sets the order accounts appear in when recording a transaction.":"Tạo, sửa hoặc ngừng kích hoạt tài khoản dùng cho giao dịch. Thứ tự ở đây cũng là thứ tự tài khoản hiển thị khi ghi giao dịch.", "Move up":"Di chuyển lên", "Move down":"Di chuyển xuống"
  , "Icon":"Biểu tượng", "Automatic (by name)":"Tự động (theo tên)", "Previous day":"Ngày trước", "Next day":"Ngày sau", "Choose date":"Chọn ngày", "Add a note":"Thêm ghi chú"
  , "Uploading...":"Đang tải lên...", "Data":"Dữ liệu", "Import and export personal finance records.":"Nhập và xuất dữ liệu tài chính cá nhân."
  , "Apply":"Đưa vào giao dịch", "Re-apply":"Đưa lại vào giao dịch", "Applying...":"Đang xử lý...", "Applied":"Đã đưa vào giao dịch", "applied":"đã đưa vào giao dịch", "rows with unmatched wallet":"dòng chưa khớp ví", "invalid rows":"dòng lỗi"
  , "Choose an account":"Vui lòng chọn tài khoản", "Enter an amount":"Vui lòng nhập số tiền", "Choose a category":"Vui lòng chọn danh mục"
  , "Delete":"Xoá", "Confirm delete":"Xác nhận xoá", "Deleting...":"Đang xoá...", "Transaction details":"Chi tiết giao dịch", "Editing transaction":"Đang sửa giao dịch", "This transaction type is managed on its own page and can't be edited or deleted here.":"Loại giao dịch này được quản lý ở trang riêng (Tiết kiệm/Tài sản) và không thể sửa hoặc xoá tại đây."
  , "Assets":"Tài sản", "Manage assets, investments, and net worth in one place.":"Quản lý tài sản, đầu tư và tài sản ròng tại một nơi."
};
export function ui(language: Language, text: string): string {
  const extra: Record<string, string> = { "Search category":"Tìm danh mục", "Collapse":"Thu gọn", "Expand":"Mở rộng", "All":"Tất cả", "Expenses":"Chi tiêu", "Income":"Thu nhập", "None":"Không có danh mục cha", "Add child category":"Thêm danh mục con", "Other / Unclassified":"Khác / Chưa phân loại", "No categories found.":"Không tìm thấy danh mục" };
  if (language === "vi" && text in extra) return extra[text];
  if (!(text in enUi)) return text;
  const key = text as UiKey;
  return language === "vi" ? viUi[key] : enUi[key];
}
export function useLanguage(): [Language, (value: Language) => void] {
  const [language, setLanguage] = useState<Language>("vi");
  useEffect(() => {
    const saved = localStorage.getItem("pf-language");
    if (saved === "vi" || saved === "en") setLanguage(saved);
  }, []);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  return [language, value => { setLanguage(value); localStorage.setItem("pf-language", value); }];
}
