"use client";
import { useEffect, useState } from "react";
export type Language = "vi" | "en";
const en = { transactions:"Transactions", accounts:"Accounts", categories:"Categories", review:"Review", portfolio:"Portfolio", title:"Personal Finance", eyebrow:"Local-first ledger", language:"Language" } as const;
const vi = { transactions:"Giao dịch", accounts:"Tài khoản", categories:"Danh mục", review:"Đối soát", portfolio:"Đầu tư", title:"Tài chính cá nhân", eyebrow:"Sổ cái lưu trữ cục bộ", language:"Ngôn ngữ" } as const;
export const copy = { en, vi } as const;
export const display = {
  en: (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, c => c.toUpperCase()),
  vi: (value: string) => ({ CASH:"Tiền mặt", BANK:"Ngân hàng", CREDIT_CARD:"Thẻ tín dụng", EWALLET:"Ví điện tử", EXPENSE:"Chi tiêu", INCOME:"Thu nhập", TRANSFER:"Chuyển tiền", CREDIT_CARD_PAYMENT:"Thanh toán thẻ tín dụng", INTEREST:"Tiền lãi", SAVINGS_DEPOSIT:"Gửi tiết kiệm", SAVINGS_WITHDRAWAL:"Rút tiết kiệm", ASSET_PURCHASE:"Mua tài sản", ASSET_SALE:"Bán tài sản", ADJUSTMENT:"Điều chỉnh", LIVE:"Trực tiếp", STALE:"Cũ", MANUAL:"Nhập thủ công", UNAVAILABLE:"Không khả dụng" } as Record<string,string>)[value] ?? value,
} as const;
export function enumLabel(language: Language, value: string): string {
  return display[language](value);
}
export const defaultCategoryLabels = {
  "Expenses":"Chi tiêu", "Income":"Thu nhập", "Food & Drinks":"Ăn uống", "Groceries":"Đi chợ / Siêu thị", "Eating Out":"Ăn ngoài", "Coffee & Drinks":"Cà phê & Đồ uống", "Bills & Utilities":"Hóa đơn & Tiện ích", "Electricity":"Điện", "Water":"Nước", "Internet":"Internet", "Mobile Phone":"Điện thoại di động", "Rent":"Tiền thuê nhà", "Gas":"Gas / Khí đốt", "Transportation":"Di chuyển", "Fuel":"Nhiên liệu", "Parking":"Gửi xe", "Taxi & Ride-hailing":"Taxi & Xe công nghệ", "Public Transport":"Phương tiện công cộng", "Vehicle Maintenance":"Bảo dưỡng xe", "Shopping":"Mua sắm", "Clothing":"Quần áo", "Electronics":"Điện tử", "Personal Items":"Đồ dùng cá nhân", "Household":"Đồ gia dụng", "Home & Family":"Nhà cửa & Gia đình", "Home Maintenance":"Bảo trì nhà cửa", "Family":"Gia đình", "Children":"Con cái", "Pets":"Thú cưng", "Health & Fitness":"Sức khỏe", "Medical":"Khám chữa bệnh", "Pharmacy":"Thuốc", "Fitness":"Thể dục", "Entertainment":"Giải trí", "Movies & Events":"Phim & Sự kiện", "Games":"Trò chơi", "Subscriptions":"Dịch vụ đăng ký", "Hobbies":"Sở thích", "Education":"Giáo dục", "Tuition":"Học phí", "Books":"Sách", "Courses":"Khóa học", "Travel":"Du lịch", "Flights":"Vé máy bay", "Accommodation":"Lưu trú", "Local Transport":"Di chuyển tại điểm đến", "Activities":"Hoạt động", "Gifts & Donations":"Quà tặng & Từ thiện", "Gifts":"Quà tặng", "Charity":"Từ thiện", "Insurance":"Bảo hiểm", "Taxes & Fees":"Thuế & Phí", "Other Expense":"Chi tiêu khác", "Salary":"Lương", "Bonus":"Thưởng", "Business Income":"Thu nhập kinh doanh", "Investment Income":"Thu nhập đầu tư", "Interest":"Tiền lãi", "Gifts Received":"Quà tặng nhận được", "Refunds":"Hoàn tiền", "Other Income":"Thu nhập khác"
} as const;
export function categoryLabel(language: Language, name: string): string {
  return language === "vi" && name in defaultCategoryLabels ? defaultCategoryLabels[name as keyof typeof defaultCategoryLabels] : name;
}
const viUi: Record<string, string> = {
  "Main navigation":"Điều hướng chính", "Import & reconciliation review":"Xem lại nhập liệu & đối soát", "Persisted import batches and reconciliation candidates.":"Các đợt nhập liệu và ứng viên đối soát đã lưu.", "Import batches":"Các đợt nhập liệu", "No import batches yet.":"Chưa có đợt nhập liệu nào.", "Reconciliation candidates":"Ứng viên đối soát", "No reconciliation candidates yet.":"Chưa có ứng viên đối soát nào.", "Raw row":"Dòng thô", "Event":"Sự kiện", "rows":"dòng", "Portfolio & net worth":"Danh mục đầu tư & tài sản ròng", "Current persisted balances and accepted valuations.":"Số dư đã lưu và định giá được chấp nhận hiện tại.", "Net worth":"Tài sản ròng", "Accounts in scope":"Tài khoản trong phạm vi", "Invested assets":"Tài sản đầu tư", "Valuation incomplete":"Định giá chưa đầy đủ", "Valuation incomplete: one or more invested assets has no usable quote.":"Định giá chưa đầy đủ: một hoặc nhiều tài sản đầu tư không có báo giá dùng được.", "Valuation unavailable":"Không thể định giá", "Savings":"Tiết kiệm", "Credit cards":"Thẻ tín dụng", "Precious metals":"Kim loại quý", "Crypto":"Tiền mã hóa", "No savings yet.":"Chưa có khoản tiết kiệm nào.", "No credit cards yet.":"Chưa có thẻ tín dụng nào.", "No precious metals yet.":"Chưa có kim loại quý nào.", "No crypto yet.":"Chưa có tiền mã hóa nào.", "Accounts":"Tài khoản", "Create, edit, or deactivate the accounts used by ledger entries.":"Tạo, sửa hoặc ngừng kích hoạt tài khoản dùng cho bút toán.", "Name":"Tên", "Type":"Loại", "Currency":"Tiền tệ", "Save changes":"Lưu thay đổi", "Add account":"Thêm tài khoản", "Cancel":"Hủy", "No accounts yet.":"Chưa có tài khoản nào.", "Edit":"Sửa", "Deactivate":"Ngừng kích hoạt", "Activate":"Kích hoạt", "Categories":"Danh mục", "Organize events into an optional hierarchy.":"Sắp xếp sự kiện theo hệ thống phân cấp tùy chọn.", "Parent":"Danh mục cha", "None":"Không có", "Add category":"Thêm danh mục", "No categories yet.":"Chưa có danh mục nào.", "Top level":"Cấp cao nhất", "Transactions":"Giao dịch", "Record events with exact signed decimal amounts; validation and balances remain on the server.":"Ghi sự kiện với số tiền thập phân có dấu chính xác; máy chủ chịu trách nhiệm xác thực và số dư.", "Date":"Ngày", "Category":"Danh mục", "Payee":"Người nhận", "Trip / event":"Chuyến đi / sự kiện", "Note":"Ghi chú", "Account entries":"Các bút toán tài khoản", "Select account":"Chọn tài khoản", "Signed amount":"Số tiền có dấu", "Remove":"Xóa", "Add another entry":"Thêm bút toán", "Record transaction":"Ghi giao dịch", "No transactions yet.":"Chưa có giao dịch nào.", "Details":"Chi tiết", "Entries":"Bút toán", "Saving…":"Đang lưu…", "Active":"Đang hoạt động", "Inactive":"Ngừng hoạt động", "Loading…":"Đang tải…", "No provider":"Không có nhà cung cấp", "No quote timestamp":"Không có thời điểm báo giá"
};
export function ui(language: Language, text: string): string { return language === "vi" ? viUi[text] ?? text : text; }
export function useLanguage(): [Language, (value: Language) => void] {
  const [language, setLanguage] = useState<Language>("vi");
  useEffect(() => {
    const saved = localStorage.getItem("pf-language");
    if (saved === "vi" || saved === "en") setLanguage(saved);
  }, []);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  return [language, value => { setLanguage(value); localStorage.setItem("pf-language", value); }];
}
